import os
from googlesearch import search

import requests

def main():
    # search string
    q = input("What do you want to search up?: ")

    # For the search history file, opens and writes the results
    with open(f"{q}_Google_OSINT.txt", "w") as google_results:
            google_results.write("Generated by 1cy0sint - 1cy5p0ng3b0b")
            google_results.write("""
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
░░███╗░░░█████╗░██╗░░░██╗░░░░░░░█████╗░░██████╗██╗███╗░░██╗████████╗
░████║░░██╔══██╗╚██╗░██╔╝░░░░░░██╔══██╗██╔════╝██║████╗░██║╚══██╔══╝
██╔██║░░██║░░╚═╝░╚████╔╝░█████╗██║░░██║╚█████╗░██║██╔██╗██║░░░██║░░░
╚═╝██║░░██║░░██╗░░╚██╔╝░░╚════╝██║░░██║░╚═══██╗██║██║╚████║░░░██║░░░
███████╗╚█████╔╝░░░██║░░░░░░░░░╚█████╔╝██████╔╝██║██║░╚███║░░░██║░░░
╚══════╝░╚════╝░░░░╚═╝░░░░░░░░░░╚════╝░╚═════╝░╚═╝╚═╝░░╚══╝░░░╚═╝░░░
░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
""")
            google_results.write("https://github.com/CollinEdward/1CY-OSINT\n\n")
    with open(f"{q}_Google_OSINT.txt", "a") as google_results:
        for x in search(q, num=20, pause=2):
            request = requests.get(x)
            google_results.write(f"--> " + x + " <--"+str(request)+"-->" + "\n")


if __name__ == '__main__':
    main()
